# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20161101_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='UID',
            field=models.CharField(default='0,0,0,0', max_length=30),
        ),
    ]
